### PR TITLE
Create style.css

### PR DESCRIPTION
**Pull request by Cristofer543**

### CODE REVIEW

**Comment by Tyson3101** [comment]
Thank you very much for this, it does look a lot better.

**Comment by Cristofer543** [comment]
> Thank you very much for this, it does look a lot better. It has been merged, and published with small adjustments.

Thank

**Comment by Cristofer543** [comment]
By the way update it in the chrome store because it is not updated or anything, and change the old photos.

**Comment by Tyson3101** [comment]
I have published it to the chrome store, but the review process taking longer than usual.
And yes, I do need to change the old photos. 
Thanks again!

**Pull request merged**
